---
name: 🩺 Debug
"on":
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/debug.yaml
  schedule:
    - cron: "0 12 1 * *"

jobs:

  debug:
    uses: kdeldycke/repomatic/.github/workflows/debug.yaml@66650046de54a8032f4c38358b7ef8c9ae39e7b5 # v7.11.0
