---
name: Labels
"on":
  # Only the develop branch has authority on the project management. This will
  # prevent any other tagging or release activity interfer with the project.
  push:
    branches:
      - develop

jobs:

  labels:
    name: Sync labels
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Sync labels
        uses: lannonbr/issue-label-manager-action@3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
