---
name: Labeller (content-based)
"on":
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:

  labeller:
    uses: kdeldycke/workflows/.github/workflows/labeller-file-based.yaml@v4.19.1