---
name: Lint
"on":
  push:
    # QA on main is too late: we shouldn't mess with the code at this point.
    branches-ignore:
      - 'main'
  pull_request:

jobs:

  lint-python:
    name: Lint and check Python code
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.2
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry
          poetry install
      - name: Lint
        run: |
          poetry run pylint mail_deduplicate

  lint-yaml:
    name: Lint YAML files
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.2
      - name: Install linter
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry
          poetry install
      - name: Lint
        run: |
          poetry run yamllint .
